// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://leitdruviywukfrgrizj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlaXRkcnV2aXl3dWtmcmdyaXpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzMwODcsImV4cCI6MjA2MDY0OTA4N30.JO_1cX_UD9Il8Tlbq4zQNNgE8-1UO7HXxVeFZs09myc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);